#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OMAPGMap.Droid.Resource", IsApplication=true)]

namespace OMAPGMap.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Microsoft.AppCenter.Push.Android.Resource.String.library_name = global::OMAPGMap.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f01001a
			public const int buttonSize = 2130771994;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010012
			public const int cameraMaxZoomPreference = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int cameraMinZoomPreference = 2130771985;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010019
			public const int circleCrop = 2130771993;
			
			// aapt resource value: 0x7f01001b
			public const int colorScheme = 2130771995;
			
			// aapt resource value: 0x7f010024
			public const int font = 2130772004;
			
			// aapt resource value: 0x7f01001d
			public const int fontProviderAuthority = 2130771997;
			
			// aapt resource value: 0x7f010020
			public const int fontProviderCerts = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int fontProviderFetchStrategy = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int fontProviderFetchTimeout = 2130772002;
			
			// aapt resource value: 0x7f01001e
			public const int fontProviderPackage = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int fontProviderQuery = 2130771999;
			
			// aapt resource value: 0x7f010023
			public const int fontStyle = 2130772003;
			
			// aapt resource value: 0x7f010025
			public const int fontWeight = 2130772005;
			
			// aapt resource value: 0x7f010018
			public const int imageAspectRatio = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int imageAspectRatioAdjust = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int latLngBoundsNorthEastLatitude = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int latLngBoundsNorthEastLongitude = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int latLngBoundsSouthWestLatitude = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int latLngBoundsSouthWestLongitude = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f01001c
			public const int scopeUris = 2130771996;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public const int abc_action_bar_embed_tabs = 2131296256;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f07000f
			public const int common_google_signin_btn_text_dark = 2131165199;
			
			// aapt resource value: 0x7f070000
			public const int common_google_signin_btn_text_dark_default = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int common_google_signin_btn_text_dark_disabled = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int common_google_signin_btn_text_dark_focused = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int common_google_signin_btn_text_dark_pressed = 2131165187;
			
			// aapt resource value: 0x7f070010
			public const int common_google_signin_btn_text_light = 2131165200;
			
			// aapt resource value: 0x7f070004
			public const int common_google_signin_btn_text_light_default = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int common_google_signin_btn_text_light_disabled = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int common_google_signin_btn_text_light_focused = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int common_google_signin_btn_text_light_pressed = 2131165191;
			
			// aapt resource value: 0x7f070011
			public const int common_google_signin_btn_tint = 2131165201;
			
			// aapt resource value: 0x7f07000b
			public const int notification_action_color_filter = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int notification_icon_bg_color = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int notification_material_background_media_default_color = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int primary_text_default_material_dark = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int ripple_material_light = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int secondary_text_default_material_dark = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int secondary_text_default_material_light = 2131165198;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0004
			public const int compat_button_inset_horizontal_material = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int compat_button_inset_vertical_material = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int compat_button_padding_horizontal_material = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int compat_button_padding_vertical_material = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int compat_control_corner_material = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int notification_action_icon_size = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int notification_action_text_size = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int notification_big_circle_margin = 2131361803;
			
			// aapt resource value: 0x7f0a0001
			public const int notification_content_margin_start = 2131361793;
			
			// aapt resource value: 0x7f0a000c
			public const int notification_large_icon_height = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int notification_large_icon_width = 2131361805;
			
			// aapt resource value: 0x7f0a0002
			public const int notification_main_column_padding_top = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int notification_media_narrow_margin = 2131361795;
			
			// aapt resource value: 0x7f0a000e
			public const int notification_right_icon_size = 2131361806;
			
			// aapt resource value: 0x7f0a0000
			public const int notification_right_side_padding_top = 2131361792;
			
			// aapt resource value: 0x7f0a000f
			public const int notification_small_icon_background_padding = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int notification_small_icon_size_as_large = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int notification_subtext_size = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int notification_top_pad = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int notification_top_pad_large_text = 2131361811;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_focused = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_disabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_focused = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_text_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_normal_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_normal_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int googleg_disabled_color_18 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int googleg_standard_color_18 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int notification_action_background = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int notification_bg = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int notification_bg_low = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int notification_bg_low_normal = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int notification_bg_low_pressed = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int notification_bg_normal = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int notification_bg_normal_pressed = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int notification_icon_background = 2130837532;
			
			// aapt resource value: 0x7f02001f
			public const int notification_template_icon_bg = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int notification_template_icon_low_bg = 2130837536;
			
			// aapt resource value: 0x7f02001d
			public const int notification_tile_bg = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int notify_panel_notification_icon_bg = 2130837534;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b001c
			public const int action0 = 2131427356;
			
			// aapt resource value: 0x7f0b0019
			public const int action_container = 2131427353;
			
			// aapt resource value: 0x7f0b0020
			public const int action_divider = 2131427360;
			
			// aapt resource value: 0x7f0b001a
			public const int action_image = 2131427354;
			
			// aapt resource value: 0x7f0b001b
			public const int action_text = 2131427355;
			
			// aapt resource value: 0x7f0b002a
			public const int actions = 2131427370;
			
			// aapt resource value: 0x7f0b000a
			public const int adjust_height = 2131427338;
			
			// aapt resource value: 0x7f0b000b
			public const int adjust_width = 2131427339;
			
			// aapt resource value: 0x7f0b0012
			public const int async = 2131427346;
			
			// aapt resource value: 0x7f0b000f
			public const int auto = 2131427343;
			
			// aapt resource value: 0x7f0b0013
			public const int blocking = 2131427347;
			
			// aapt resource value: 0x7f0b001d
			public const int cancel_action = 2131427357;
			
			// aapt resource value: 0x7f0b0025
			public const int chronometer = 2131427365;
			
			// aapt resource value: 0x7f0b0010
			public const int dark = 2131427344;
			
			// aapt resource value: 0x7f0b0017
			public const int editText1 = 2131427351;
			
			// aapt resource value: 0x7f0b002c
			public const int end_padder = 2131427372;
			
			// aapt resource value: 0x7f0b0014
			public const int forever = 2131427348;
			
			// aapt resource value: 0x7f0b0005
			public const int hybrid = 2131427333;
			
			// aapt resource value: 0x7f0b0027
			public const int icon = 2131427367;
			
			// aapt resource value: 0x7f0b002b
			public const int icon_group = 2131427371;
			
			// aapt resource value: 0x7f0b000c
			public const int icon_only = 2131427340;
			
			// aapt resource value: 0x7f0b0026
			public const int info = 2131427366;
			
			// aapt resource value: 0x7f0b0015
			public const int italic = 2131427349;
			
			// aapt resource value: 0x7f0b0011
			public const int light = 2131427345;
			
			// aapt resource value: 0x7f0b0000
			public const int line1 = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int line3 = 2131427329;
			
			// aapt resource value: 0x7f0b0018
			public const int map = 2131427352;
			
			// aapt resource value: 0x7f0b001f
			public const int media_actions = 2131427359;
			
			// aapt resource value: 0x7f0b0006
			public const int none = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int normal = 2131427335;
			
			// aapt resource value: 0x7f0b0029
			public const int notification_background = 2131427369;
			
			// aapt resource value: 0x7f0b0022
			public const int notification_main_column = 2131427362;
			
			// aapt resource value: 0x7f0b0021
			public const int notification_main_column_container = 2131427361;
			
			// aapt resource value: 0x7f0b0028
			public const int right_icon = 2131427368;
			
			// aapt resource value: 0x7f0b0023
			public const int right_side = 2131427363;
			
			// aapt resource value: 0x7f0b0008
			public const int satellite = 2131427336;
			
			// aapt resource value: 0x7f0b000d
			public const int standard = 2131427341;
			
			// aapt resource value: 0x7f0b001e
			public const int status_bar_latest_event_content = 2131427358;
			
			// aapt resource value: 0x7f0b0009
			public const int terrain = 2131427337;
			
			// aapt resource value: 0x7f0b0002
			public const int text = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int text2 = 2131427331;
			
			// aapt resource value: 0x7f0b0024
			public const int time = 2131427364;
			
			// aapt resource value: 0x7f0b0004
			public const int title = 2131427332;
			
			// aapt resource value: 0x7f0b0016
			public const int username = 2131427350;
			
			// aapt resource value: 0x7f0b000e
			public const int wide = 2131427342;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050001
			public const int cancel_button_image_alpha = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int status_bar_notification_info_maxnum = 2131034114;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Login = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int notification_action = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int notification_action_tombstone = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int notification_media_action = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_media_cancel_action = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int notification_template_big_media = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int notification_template_big_media_custom = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int notification_template_big_media_narrow = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int notification_template_big_media_narrow_custom = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int notification_template_custom_big = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int notification_template_icon_group = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int notification_template_lines_media = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int notification_template_media = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int notification_template_media_custom = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int notification_template_part_chronometer = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int notification_template_part_time = 2130968592;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int 001 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int 002 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int 003 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int 004 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int 005 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int 006 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int 007 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int 008 = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int 009 = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int 010 = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int 011 = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int 012 = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int 013 = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int 014 = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int 015 = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int 016 = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int 017 = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int 018 = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int 019 = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int 020 = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int 021 = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int 022 = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int 023 = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int 024 = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int 025 = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int 026 = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int 027 = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int 028 = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int 029 = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int 030 = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int 031 = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int 032 = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int 033 = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int 034 = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int 035 = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int 036 = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int 037 = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int 038 = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int 039 = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int 040 = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int 041 = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int 042 = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int 043 = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int 044 = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int 045 = 2130903084;
			
			// aapt resource value: 0x7f03002d
			public const int 046 = 2130903085;
			
			// aapt resource value: 0x7f03002e
			public const int 047 = 2130903086;
			
			// aapt resource value: 0x7f03002f
			public const int 048 = 2130903087;
			
			// aapt resource value: 0x7f030030
			public const int 049 = 2130903088;
			
			// aapt resource value: 0x7f030031
			public const int 050 = 2130903089;
			
			// aapt resource value: 0x7f030032
			public const int 051 = 2130903090;
			
			// aapt resource value: 0x7f030033
			public const int 052 = 2130903091;
			
			// aapt resource value: 0x7f030034
			public const int 053 = 2130903092;
			
			// aapt resource value: 0x7f030035
			public const int 054 = 2130903093;
			
			// aapt resource value: 0x7f030036
			public const int 055 = 2130903094;
			
			// aapt resource value: 0x7f030037
			public const int 056 = 2130903095;
			
			// aapt resource value: 0x7f030038
			public const int 057 = 2130903096;
			
			// aapt resource value: 0x7f030039
			public const int 058 = 2130903097;
			
			// aapt resource value: 0x7f03003a
			public const int 059 = 2130903098;
			
			// aapt resource value: 0x7f03003b
			public const int 060 = 2130903099;
			
			// aapt resource value: 0x7f03003c
			public const int 061 = 2130903100;
			
			// aapt resource value: 0x7f03003d
			public const int 062 = 2130903101;
			
			// aapt resource value: 0x7f03003e
			public const int 063 = 2130903102;
			
			// aapt resource value: 0x7f03003f
			public const int 064 = 2130903103;
			
			// aapt resource value: 0x7f030040
			public const int 065 = 2130903104;
			
			// aapt resource value: 0x7f030041
			public const int 066 = 2130903105;
			
			// aapt resource value: 0x7f030042
			public const int 067 = 2130903106;
			
			// aapt resource value: 0x7f030043
			public const int 068 = 2130903107;
			
			// aapt resource value: 0x7f030044
			public const int 069 = 2130903108;
			
			// aapt resource value: 0x7f030045
			public const int 070 = 2130903109;
			
			// aapt resource value: 0x7f030046
			public const int 071 = 2130903110;
			
			// aapt resource value: 0x7f030047
			public const int 072 = 2130903111;
			
			// aapt resource value: 0x7f030048
			public const int 073 = 2130903112;
			
			// aapt resource value: 0x7f030049
			public const int 074 = 2130903113;
			
			// aapt resource value: 0x7f03004a
			public const int 075 = 2130903114;
			
			// aapt resource value: 0x7f03004b
			public const int 076 = 2130903115;
			
			// aapt resource value: 0x7f03004c
			public const int 077 = 2130903116;
			
			// aapt resource value: 0x7f03004d
			public const int 078 = 2130903117;
			
			// aapt resource value: 0x7f03004e
			public const int 079 = 2130903118;
			
			// aapt resource value: 0x7f03004f
			public const int 080 = 2130903119;
			
			// aapt resource value: 0x7f030050
			public const int 081 = 2130903120;
			
			// aapt resource value: 0x7f030051
			public const int 082 = 2130903121;
			
			// aapt resource value: 0x7f030052
			public const int 083 = 2130903122;
			
			// aapt resource value: 0x7f030053
			public const int 084 = 2130903123;
			
			// aapt resource value: 0x7f030054
			public const int 085 = 2130903124;
			
			// aapt resource value: 0x7f030055
			public const int 086 = 2130903125;
			
			// aapt resource value: 0x7f030056
			public const int 087 = 2130903126;
			
			// aapt resource value: 0x7f030057
			public const int 088 = 2130903127;
			
			// aapt resource value: 0x7f030058
			public const int 089 = 2130903128;
			
			// aapt resource value: 0x7f030059
			public const int 090 = 2130903129;
			
			// aapt resource value: 0x7f03005a
			public const int 091 = 2130903130;
			
			// aapt resource value: 0x7f03005b
			public const int 092 = 2130903131;
			
			// aapt resource value: 0x7f03005c
			public const int 093 = 2130903132;
			
			// aapt resource value: 0x7f03005d
			public const int 094 = 2130903133;
			
			// aapt resource value: 0x7f03005e
			public const int 095 = 2130903134;
			
			// aapt resource value: 0x7f03005f
			public const int 096 = 2130903135;
			
			// aapt resource value: 0x7f030060
			public const int 097 = 2130903136;
			
			// aapt resource value: 0x7f030061
			public const int 098 = 2130903137;
			
			// aapt resource value: 0x7f030062
			public const int 099 = 2130903138;
			
			// aapt resource value: 0x7f030063
			public const int 100 = 2130903139;
			
			// aapt resource value: 0x7f030064
			public const int 101 = 2130903140;
			
			// aapt resource value: 0x7f030065
			public const int 102 = 2130903141;
			
			// aapt resource value: 0x7f030066
			public const int 103 = 2130903142;
			
			// aapt resource value: 0x7f030067
			public const int 104 = 2130903143;
			
			// aapt resource value: 0x7f030068
			public const int 105 = 2130903144;
			
			// aapt resource value: 0x7f030069
			public const int 106 = 2130903145;
			
			// aapt resource value: 0x7f03006a
			public const int 107 = 2130903146;
			
			// aapt resource value: 0x7f03006b
			public const int 108 = 2130903147;
			
			// aapt resource value: 0x7f03006c
			public const int 109 = 2130903148;
			
			// aapt resource value: 0x7f03006d
			public const int 110 = 2130903149;
			
			// aapt resource value: 0x7f03006e
			public const int 111 = 2130903150;
			
			// aapt resource value: 0x7f03006f
			public const int 112 = 2130903151;
			
			// aapt resource value: 0x7f030070
			public const int 113 = 2130903152;
			
			// aapt resource value: 0x7f030071
			public const int 114 = 2130903153;
			
			// aapt resource value: 0x7f030072
			public const int 115 = 2130903154;
			
			// aapt resource value: 0x7f030073
			public const int 116 = 2130903155;
			
			// aapt resource value: 0x7f030074
			public const int 117 = 2130903156;
			
			// aapt resource value: 0x7f030075
			public const int 118 = 2130903157;
			
			// aapt resource value: 0x7f030076
			public const int 119 = 2130903158;
			
			// aapt resource value: 0x7f030077
			public const int 120 = 2130903159;
			
			// aapt resource value: 0x7f030078
			public const int 121 = 2130903160;
			
			// aapt resource value: 0x7f030079
			public const int 122 = 2130903161;
			
			// aapt resource value: 0x7f03007a
			public const int 123 = 2130903162;
			
			// aapt resource value: 0x7f03007b
			public const int 124 = 2130903163;
			
			// aapt resource value: 0x7f03007c
			public const int 125 = 2130903164;
			
			// aapt resource value: 0x7f03007d
			public const int 126 = 2130903165;
			
			// aapt resource value: 0x7f03007e
			public const int 127 = 2130903166;
			
			// aapt resource value: 0x7f03007f
			public const int 128 = 2130903167;
			
			// aapt resource value: 0x7f030080
			public const int 129 = 2130903168;
			
			// aapt resource value: 0x7f030081
			public const int 130 = 2130903169;
			
			// aapt resource value: 0x7f030082
			public const int 131 = 2130903170;
			
			// aapt resource value: 0x7f030083
			public const int 132 = 2130903171;
			
			// aapt resource value: 0x7f030084
			public const int 133 = 2130903172;
			
			// aapt resource value: 0x7f030085
			public const int 134 = 2130903173;
			
			// aapt resource value: 0x7f030086
			public const int 135 = 2130903174;
			
			// aapt resource value: 0x7f030087
			public const int 136 = 2130903175;
			
			// aapt resource value: 0x7f030088
			public const int 137 = 2130903176;
			
			// aapt resource value: 0x7f030089
			public const int 138 = 2130903177;
			
			// aapt resource value: 0x7f03008a
			public const int 139 = 2130903178;
			
			// aapt resource value: 0x7f03008b
			public const int 140 = 2130903179;
			
			// aapt resource value: 0x7f03008c
			public const int 141 = 2130903180;
			
			// aapt resource value: 0x7f03008d
			public const int 142 = 2130903181;
			
			// aapt resource value: 0x7f03008e
			public const int 143 = 2130903182;
			
			// aapt resource value: 0x7f03008f
			public const int 144 = 2130903183;
			
			// aapt resource value: 0x7f030090
			public const int 145 = 2130903184;
			
			// aapt resource value: 0x7f030091
			public const int 146 = 2130903185;
			
			// aapt resource value: 0x7f030092
			public const int 147 = 2130903186;
			
			// aapt resource value: 0x7f030093
			public const int 148 = 2130903187;
			
			// aapt resource value: 0x7f030094
			public const int 149 = 2130903188;
			
			// aapt resource value: 0x7f030095
			public const int 150 = 2130903189;
			
			// aapt resource value: 0x7f030096
			public const int 151 = 2130903190;
			
			// aapt resource value: 0x7f030097
			public const int 152 = 2130903191;
			
			// aapt resource value: 0x7f030098
			public const int 153 = 2130903192;
			
			// aapt resource value: 0x7f030099
			public const int 154 = 2130903193;
			
			// aapt resource value: 0x7f03009a
			public const int 155 = 2130903194;
			
			// aapt resource value: 0x7f03009b
			public const int 156 = 2130903195;
			
			// aapt resource value: 0x7f03009c
			public const int 157 = 2130903196;
			
			// aapt resource value: 0x7f03009d
			public const int 158 = 2130903197;
			
			// aapt resource value: 0x7f03009e
			public const int 159 = 2130903198;
			
			// aapt resource value: 0x7f03009f
			public const int 160 = 2130903199;
			
			// aapt resource value: 0x7f0300a0
			public const int 161 = 2130903200;
			
			// aapt resource value: 0x7f0300a1
			public const int 162 = 2130903201;
			
			// aapt resource value: 0x7f0300a2
			public const int 163 = 2130903202;
			
			// aapt resource value: 0x7f0300a3
			public const int 164 = 2130903203;
			
			// aapt resource value: 0x7f0300a4
			public const int 165 = 2130903204;
			
			// aapt resource value: 0x7f0300a5
			public const int 166 = 2130903205;
			
			// aapt resource value: 0x7f0300a6
			public const int 167 = 2130903206;
			
			// aapt resource value: 0x7f0300a7
			public const int 168 = 2130903207;
			
			// aapt resource value: 0x7f0300a8
			public const int 169 = 2130903208;
			
			// aapt resource value: 0x7f0300a9
			public const int 170 = 2130903209;
			
			// aapt resource value: 0x7f0300aa
			public const int 171 = 2130903210;
			
			// aapt resource value: 0x7f0300ab
			public const int 172 = 2130903211;
			
			// aapt resource value: 0x7f0300ac
			public const int 173 = 2130903212;
			
			// aapt resource value: 0x7f0300ad
			public const int 174 = 2130903213;
			
			// aapt resource value: 0x7f0300ae
			public const int 175 = 2130903214;
			
			// aapt resource value: 0x7f0300af
			public const int 176 = 2130903215;
			
			// aapt resource value: 0x7f0300b0
			public const int 177 = 2130903216;
			
			// aapt resource value: 0x7f0300b1
			public const int 178 = 2130903217;
			
			// aapt resource value: 0x7f0300b2
			public const int 179 = 2130903218;
			
			// aapt resource value: 0x7f0300b3
			public const int 180 = 2130903219;
			
			// aapt resource value: 0x7f0300b4
			public const int 181 = 2130903220;
			
			// aapt resource value: 0x7f0300b5
			public const int 182 = 2130903221;
			
			// aapt resource value: 0x7f0300b6
			public const int 183 = 2130903222;
			
			// aapt resource value: 0x7f0300b7
			public const int 184 = 2130903223;
			
			// aapt resource value: 0x7f0300b8
			public const int 185 = 2130903224;
			
			// aapt resource value: 0x7f0300b9
			public const int 186 = 2130903225;
			
			// aapt resource value: 0x7f0300ba
			public const int 187 = 2130903226;
			
			// aapt resource value: 0x7f0300bb
			public const int 188 = 2130903227;
			
			// aapt resource value: 0x7f0300bc
			public const int 189 = 2130903228;
			
			// aapt resource value: 0x7f0300bd
			public const int 190 = 2130903229;
			
			// aapt resource value: 0x7f0300be
			public const int 191 = 2130903230;
			
			// aapt resource value: 0x7f0300bf
			public const int 192 = 2130903231;
			
			// aapt resource value: 0x7f0300c0
			public const int 193 = 2130903232;
			
			// aapt resource value: 0x7f0300c1
			public const int 194 = 2130903233;
			
			// aapt resource value: 0x7f0300c2
			public const int 195 = 2130903234;
			
			// aapt resource value: 0x7f0300c3
			public const int 196 = 2130903235;
			
			// aapt resource value: 0x7f0300c4
			public const int 197 = 2130903236;
			
			// aapt resource value: 0x7f0300c5
			public const int 198 = 2130903237;
			
			// aapt resource value: 0x7f0300c6
			public const int 199 = 2130903238;
			
			// aapt resource value: 0x7f0300c7
			public const int 200 = 2130903239;
			
			// aapt resource value: 0x7f0300c8
			public const int 202 = 2130903240;
			
			// aapt resource value: 0x7f0300c9
			public const int 203 = 2130903241;
			
			// aapt resource value: 0x7f0300ca
			public const int 204 = 2130903242;
			
			// aapt resource value: 0x7f0300cb
			public const int 205 = 2130903243;
			
			// aapt resource value: 0x7f0300cc
			public const int 206 = 2130903244;
			
			// aapt resource value: 0x7f0300cd
			public const int 207 = 2130903245;
			
			// aapt resource value: 0x7f0300ce
			public const int 208 = 2130903246;
			
			// aapt resource value: 0x7f0300cf
			public const int 209 = 2130903247;
			
			// aapt resource value: 0x7f0300d0
			public const int 210 = 2130903248;
			
			// aapt resource value: 0x7f0300d1
			public const int 211 = 2130903249;
			
			// aapt resource value: 0x7f0300d2
			public const int 212 = 2130903250;
			
			// aapt resource value: 0x7f0300d3
			public const int 213 = 2130903251;
			
			// aapt resource value: 0x7f0300d4
			public const int 214 = 2130903252;
			
			// aapt resource value: 0x7f0300d5
			public const int 215 = 2130903253;
			
			// aapt resource value: 0x7f0300d6
			public const int 216 = 2130903254;
			
			// aapt resource value: 0x7f0300d7
			public const int 217 = 2130903255;
			
			// aapt resource value: 0x7f0300d8
			public const int 218 = 2130903256;
			
			// aapt resource value: 0x7f0300d9
			public const int 219 = 2130903257;
			
			// aapt resource value: 0x7f0300da
			public const int 220 = 2130903258;
			
			// aapt resource value: 0x7f0300db
			public const int 221 = 2130903259;
			
			// aapt resource value: 0x7f0300dc
			public const int 222 = 2130903260;
			
			// aapt resource value: 0x7f0300dd
			public const int 223 = 2130903261;
			
			// aapt resource value: 0x7f0300de
			public const int 224 = 2130903262;
			
			// aapt resource value: 0x7f0300df
			public const int 225 = 2130903263;
			
			// aapt resource value: 0x7f0300e0
			public const int 226 = 2130903264;
			
			// aapt resource value: 0x7f0300e1
			public const int 227 = 2130903265;
			
			// aapt resource value: 0x7f0300e2
			public const int 228 = 2130903266;
			
			// aapt resource value: 0x7f0300e3
			public const int 229 = 2130903267;
			
			// aapt resource value: 0x7f0300e4
			public const int 230 = 2130903268;
			
			// aapt resource value: 0x7f0300e5
			public const int 231 = 2130903269;
			
			// aapt resource value: 0x7f0300e6
			public const int 232 = 2130903270;
			
			// aapt resource value: 0x7f0300e7
			public const int 233 = 2130903271;
			
			// aapt resource value: 0x7f0300e8
			public const int 234 = 2130903272;
			
			// aapt resource value: 0x7f0300e9
			public const int 235 = 2130903273;
			
			// aapt resource value: 0x7f0300ea
			public const int 236 = 2130903274;
			
			// aapt resource value: 0x7f0300eb
			public const int 237 = 2130903275;
			
			// aapt resource value: 0x7f0300ec
			public const int 238 = 2130903276;
			
			// aapt resource value: 0x7f0300ed
			public const int 239 = 2130903277;
			
			// aapt resource value: 0x7f0300ee
			public const int 240 = 2130903278;
			
			// aapt resource value: 0x7f0300ef
			public const int 241 = 2130903279;
			
			// aapt resource value: 0x7f0300f0
			public const int 242 = 2130903280;
			
			// aapt resource value: 0x7f0300f1
			public const int 243 = 2130903281;
			
			// aapt resource value: 0x7f0300f2
			public const int 244 = 2130903282;
			
			// aapt resource value: 0x7f0300f3
			public const int 245 = 2130903283;
			
			// aapt resource value: 0x7f0300f4
			public const int 246 = 2130903284;
			
			// aapt resource value: 0x7f0300f5
			public const int 247 = 2130903285;
			
			// aapt resource value: 0x7f0300f6
			public const int 248 = 2130903286;
			
			// aapt resource value: 0x7f0300f7
			public const int 249 = 2130903287;
			
			// aapt resource value: 0x7f0300f8
			public const int 250 = 2130903288;
			
			// aapt resource value: 0x7f0300f9
			public const int 251 = 2130903289;
			
			// aapt resource value: 0x7f0300fa
			public const int ic_dialog = 2130903290;
			
			// aapt resource value: 0x7f0300fb
			public const int ic_launcher = 2130903291;
			
			// aapt resource value: 0x7f0300fc
			public const int ic_list = 2130903292;
			
			// aapt resource value: 0x7f0300fd
			public const int ic_menu = 2130903293;
			
			// aapt resource value: 0x7f0300fe
			public const int ic_status = 2130903294;
			
			// aapt resource value: 0x7f0300ff
			public const int ic_tab = 2130903295;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_enable_button = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_enable_text = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_enable_title = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_install_button = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_install_text = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_install_title = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_notification_ticker = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_unknown_issue = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_unsupported_text = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_update_button = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_update_text = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_update_title = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_updating_text = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_wear_update_text = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int common_open_on_phone = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int common_signin_button_text = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int common_signin_button_text_long = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int library_name = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int status_bar_notification_info_overflow = 2131099665;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f08000c
			public const int MapTheme = 2131230732;
			
			// aapt resource value: 0x7f080005
			public const int TextAppearance_Compat_Notification = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int TextAppearance_Compat_Notification_Info = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131230720;
			
			// aapt resource value: 0x7f08000b
			public const int TextAppearance_Compat_Notification_Line2 = 2131230731;
			
			// aapt resource value: 0x7f080004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int TextAppearance_Compat_Notification_Media = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int TextAppearance_Compat_Notification_Time = 2131230727;
			
			// aapt resource value: 0x7f080002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131230722;
			
			// aapt resource value: 0x7f080008
			public const int TextAppearance_Compat_Notification_Title = 2131230728;
			
			// aapt resource value: 0x7f080003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131230723;
			
			// aapt resource value: 0x7f080009
			public const int Widget_Compat_NotificationActionContainer = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int Widget_Compat_NotificationActionText = 2131230730;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130772003,
					2130772004,
					2130772005};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 18
			public const int MapAttrs_cameraMaxZoomPreference = 18;
			
			// aapt resource value: 17
			public const int MapAttrs_cameraMinZoomPreference = 17;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 21
			public const int MapAttrs_latLngBoundsNorthEastLatitude = 21;
			
			// aapt resource value: 22
			public const int MapAttrs_latLngBoundsNorthEastLongitude = 22;
			
			// aapt resource value: 19
			public const int MapAttrs_latLngBoundsSouthWestLatitude = 19;
			
			// aapt resource value: 20
			public const int MapAttrs_latLngBoundsSouthWestLongitude = 20;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
