// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using UIKit;

namespace OMAPGMap.iOS
{
    public partial class LayerSelectorViewController : UITableViewController, IUIPopoverControllerDelegate
	{
        string[] Layers = { "Pokemon", "Gyms", "Raids", "Trash" };

		public LayerSelectorViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            PreferredContentSize = new CGSize(200, 200);
        }

        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            var cell = tableView.DequeueReusableCell("MapLayerCell", indexPath);
            cell.TextLabel.Text = Layers[indexPath.Row];
            cell.Accessory = ServiceLayer.SharedInstance.LayersEnabled[indexPath.Row] ? UITableViewCellAccessory.Checkmark : UITableViewCellAccessory.None;
            return cell;
        }

        public override nint NumberOfSections(UITableView tableView)
        {
            return 1;
        }

        public override nint RowsInSection(UITableView tableView, nint section)
        {
            return Layers.Length;
        }

        public override void RowSelected(UITableView tableView, NSIndexPath indexPath)
        {
            ServiceLayer.SharedInstance.LayersEnabled[indexPath.Row] = !ServiceLayer.SharedInstance.LayersEnabled[indexPath.Row];
            tableView.DeselectRow(indexPath, true);
            DismissViewController(true, null);
        }

	}
}
