// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using Foundation;
using OMAPGMap.Models;
using UIKit;

namespace OMAPGMap.iOS
{
	public partial class SettingsViewController : UITableViewController
	{
        public SettingsViewController(IntPtr ptr) : base(ptr)
        {
            
        }

        private List<int> TrashAdded = new List<int>();
        private List<int> TrashRemoved = new List<int>();

        public ViewController ParentVC { get; set; }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            Title = "Pokemon Filters";
            NavigationItem.LeftBarButtonItem = new UIBarButtonItem("Done", UIBarButtonItemStyle.Done, (sender, e) =>
             {
                if(TrashAdded.Count > 0)
                {
                    ParentVC.TrashAdded(TrashAdded);
                }
                if(TrashRemoved.Count > 0)
                {
                    ParentVC.TrashRemoved( TrashRemoved);
                }
                DismissViewController(true, null);
             });
            TableView.AllowsSelection = false;
        }

        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            var cell = tableView.DequeueReusableCell("FilterCell", indexPath);
            var img = cell.ViewWithTag(1) as UIImageView;
            var notifyLbl = cell.ViewWithTag(2) as UILabel;
            var notifySwitch = cell.ViewWithTag(3) as UISwitch;
            var trashLbl = cell.ViewWithTag(4) as UILabel;
            var trashSwitch = cell.ViewWithTag(5) as UISwitch;

            img.Image = UIImage.FromBundle(indexPath.Row.ToString("D3"));
            if (!ServiceLayer.SharedInstance.PokemonHidden.Contains(indexPath.Row))
            {
                img.Alpha = 1.0f;
                notifyLbl.TextColor = UIColor.Black;
				trashSwitch.Enabled = true;
                trashSwitch.On = ServiceLayer.SharedInstance.PokemonTrash.Contains(indexPath.Row);
				notifySwitch.Enabled = false;
				notifySwitch.On = false;
            } else {
                img.Alpha = 0.7f;
                notifyLbl.TextColor = UIColor.LightGray;
                trashLbl.TextColor = UIColor.LightGray;
                trashSwitch.Enabled = false;
                trashSwitch.On = false;
                notifySwitch.Enabled = false;
                notifySwitch.On = false;
            }

            return cell;
        }

        public override nint RowsInSection(UITableView tableView, nint section)
        {
            return ServiceLayer.NumberPokemon;
        }

        partial void TrashToggled(NSObject sender)
        {
            var trashSwitch = sender as UISwitch;
            var cell = trashSwitch.Superview.Superview as UITableViewCell;
            if (cell != null)
            {
                var path = TableView.IndexPathForCell(cell);
                if(trashSwitch.On)
                {
                    TrashAdded.Add(path.Row);
                    TrashRemoved.Remove(path.Row);
                    ServiceLayer.SharedInstance.PokemonTrash.Add(path.Row);
                } else 
                {
                    TrashRemoved.Add(path.Row);
                    TrashAdded.Remove(path.Row);
                    ServiceLayer.SharedInstance.PokemonTrash.Remove(path.Row);
                }
            }
        }
	}
}
