// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using Foundation;
using OMAPGMap.Models;
using UIKit;

namespace OMAPGMap.iOS
{
	public partial class SettingsViewController : UITableViewController
	{
        public SettingsViewController(IntPtr ptr) : base(ptr)
        {
            
        }

        private List<int> TrashAdded = new List<int>();
        private List<int> TrashRemoved = new List<int>();

        public ViewController ParentVC { get; set; }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            Title = "Pokemon Filters";
            NavigationItem.LeftBarButtonItem = new UIBarButtonItem("Done", UIBarButtonItemStyle.Done, (sender, e) =>
             {
                if(TrashAdded.Count > 0)
                {
                    ParentVC.TrashAdded(TrashAdded);
                }
                if(TrashRemoved.Count > 0)
                {
                    ParentVC.TrashRemoved( TrashRemoved);
                }
                DismissViewController(true, null);
             });
            TableView.AllowsSelection = false;
        }

        public override nint NumberOfSections(UITableView tableView)
        {
            return 2;
        }

        public override string TitleForHeader(UITableView tableView, nint section)
        {
            return section == 0 ? "Settings" : "Pokemon Settings";
        }

        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            if (indexPath.Section == 0)
            {
                var cell = tableView.DequeueReusableCell("ResetTrashCell", indexPath);
                var button = cell.ViewWithTag(1) as UIButton;
                button.TouchUpInside += (sender, e) => 
                {
                    for (var i = 0; i < ServiceLayer.NumberPokemon; i++)
                    {
                        if (!ServiceLayer.SharedInstance.PokemonTrash.Contains(i) && ServiceLayer.DefaultTrash.Contains(i))
                        {
                            TrashAdded.Add(i);
                        } else if(ServiceLayer.SharedInstance.PokemonTrash.Contains(i) && !ServiceLayer.DefaultTrash.Contains(i))
                        {
                            TrashRemoved.Add(i);
                        }
                    }
                    ServiceLayer.SharedInstance.PokemonTrash.Clear();
                    ServiceLayer.SharedInstance.PokemonTrash.AddRange(ServiceLayer.DefaultTrash);
                    tableView.ReloadData();
                };
                return cell;
            }
            else
            {
                var cell = tableView.DequeueReusableCell("FilterCell", indexPath);
                var img = cell.ViewWithTag(1) as UIImageView;
                var notifyLbl = cell.ViewWithTag(2) as UILabel;
                var notifySwitch = cell.ViewWithTag(3) as UISwitch;
                var trashLbl = cell.ViewWithTag(4) as UILabel;
                var trashSwitch = cell.ViewWithTag(5) as UISwitch;

                img.Image = UIImage.FromBundle(indexPath.Row.ToString("D3"));
                if (!ServiceLayer.SharedInstance.PokemonHidden.Contains(indexPath.Row))
                {
                    img.Alpha = 1.0f;
                    notifyLbl.TextColor = UIColor.Black;
                    trashLbl.TextColor = UIColor.Black;
                    trashSwitch.Enabled = true;
                    trashSwitch.On = ServiceLayer.SharedInstance.PokemonTrash.Contains(indexPath.Row);
                    notifySwitch.Enabled = false;
                    notifySwitch.On = false;
                }
                else
                {
                    img.Alpha = 0.7f;
                    notifyLbl.TextColor = UIColor.LightGray;
                    trashLbl.TextColor = UIColor.LightGray;
                    trashSwitch.Enabled = false;
                    trashSwitch.On = false;
                    notifySwitch.Enabled = false;
                    notifySwitch.On = false;
                }
                return cell;
            }
        }

        public override nint RowsInSection(UITableView tableView, nint section)
        {
            return section == 0 ? 1 : ServiceLayer.NumberPokemon;
        }

        partial void TrashToggled(NSObject sender)
        {
            var trashSwitch = sender as UISwitch;
            var cell = trashSwitch.Superview.Superview as UITableViewCell;
            if (cell != null)
            {
                var path = TableView.IndexPathForCell(cell);
                if(trashSwitch.On)
                {
                    TrashAdded.Add(path.Row);
                    TrashRemoved.Remove(path.Row);
                    ServiceLayer.SharedInstance.PokemonTrash.Add(path.Row);
                } else 
                {
                    TrashRemoved.Add(path.Row);
                    TrashAdded.Remove(path.Row);
                    ServiceLayer.SharedInstance.PokemonTrash.Remove(path.Row);
                }
            }
        }
	}
}
